# Brewfile — agentic terminal env (macOS). Install: brew bundle --file=~/dotfiles/Brewfile
brew "fish"
brew "starship"
brew "tmux"
brew "neovim"
brew "git"
brew "git-lfs"
brew "gh"
brew "delta"
brew "direnv"
brew "mise"
brew "asdf"
brew "eza"
brew "zoxide"
brew "fzf"
brew "fd"
brew "bat"
brew "ripgrep"
brew "jq"
brew "lazygit"
brew "yazi"
brew "uv"
cask "ghostty"
cask "1password-cli"
# Nerd Font. Installed by the cask; if `brew bundle` cannot satisfy it (network
# or cask unavailable), drop the JetBrainsMonoNerdFont-*.ttf files from
# https://github.com/ryanoasis/nerd-fonts/releases into ~/Library/Fonts.
cask "font-jetbrains-mono-nerd-font"
